# Profile to activate automatic seeders
# Included in application-local.properties and application-docker-dev.properties

# Seeder Configuration
# Seeders check if the database is empty before running
# It is safe to run them multiple times

# Logging for seeders
logging.level.com.vulnerable.vulnerableapp.seeder=DEBUG

